version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env_dummy
  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD